### ISSUE TITLE
Pasting in Firefox in the example doesn't have any effect

### ISSUE THREAD

**Issue by neurodynamic** [mweiss/elm-rte-toolkit#20]
Cutting and copying work fine, but pasting into the editor doesn't seem to have any effect in Firefox for OSX.

**Comment by mweiss** [comment]
Hey @neurodynamic, thank you for taking the time to log this issue.  However, I'm having trouble reproducing it.  I tried copying and pasting in Firefox 75 on Mac OSX (10.15.3) on the demo page and it works as expected: https://youtu.be/CKF3Po7toh0

Can you be more specific about the steps you took to reproduce the error?

**Comment by neurodynamic** [comment]
@mweiss Just did a bit of investigating, and woah! Very strange! For reasons I'm not sure I know enough to investigate well, it appears to be the Firefox "Dark Reader" dark mode extension that's breaking it. When I disable that, pasting works fine. No idea why a dark mode extension would mess with selection, but also this seems like probably too much of an edge case to reasonably expect to be covered, so feel free to close this issue.

**Comment by neurodynamic** [comment]
If you do have interest in investigating, [this is the extension](https://darkreader.org/), and I see a "TypeError: t is undefined" message in the console when dark mode is enabled.

**Comment by mweiss** [comment]
This appears to be an issue with the demo page, which I've uploaded with the fix in #21.

Longer story:   Elm's virtual DOM will crash if it gets out of sync in certain ways with the real DOM, and dark reader inserts style elements of its own into the body of the document.  Since I had the font-awesome styles at the top of the body of the demo, dark reader inserted another element after it.  Apparently a lot of Elm apps can be effected by this: https://discourse.elm-lang.org/t/runtime-errors-caused-by-chrome-extensions/4381, and the ugly workaround is to wrap style elements in a div to stop the vdom from crashing.

**Comment by neurodynamic** [comment]
@mweiss Huh; every now and then bugs turn out to be really fascinating!
